version: "3"
services: 
  client: 
    image: "oscarsidebo/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "oscarsidebo/multi-server"
    mem_limit: 128m
    hostname: api
    environment: 
      - redisHost=$REDIS_HOST
      - redisPort=$REDIS_PORT
      - pgUser=$PGUSER
      - pgHost=$PGHOST
      - pgDatabase=$PGDATABASE
      - pgPassword=$PGPASSWORD
      - pgPort=$PGPORT
  worker:
    image: "oscarsidebo/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "oscarsidebo/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports: 
      - "80:80"

