name: Aws
on: 
  push: 
    branches: [ master ] 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build production react app
        run: docker build -t oscarsidebo/multi-client ./client

      - name: Build produciton server
        run: docker build -t oscarsidebo/multi-server ./server

      - name: Build production nginx
        run: docker build -t oscarsidebo/multi-nginx ./nginx


      - name: Build production worker
        run: docker build -t oscarsidebo/multi-worker ./worker

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push react app
        run: docker push oscarsidebo/multi-client


      - name: Push server
        run: docker push oscarsidebo/multi-server


      - name: Push nginx
        run: docker push oscarsidebo/multi-nginx


      - name: Push worker
        run: docker push oscarsidebo/multi-worker


  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with: 
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: Docker Complex
          environment_name: Dockercomplex-env
          version_label: 1
          region: us-west-2
          deployment_package: deploy.zip
