name: Aws
on: 
  workflow_run: 
    workflows: ["Docker Flow"] 
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build production react app
        run: docker build -t oscarsidebo/multi-client ./client

      - name: Build produciton server
        run: docker build -t oscarsidebo/multi-server ./server

      - name: Build production nginx
        run: docker build -t oscarsidebo/multi-nginx ./nginx


      - name: Build production worker
        run: docker build -t oscarsidebo/multi-worked ./worker

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push react app
        run: docker push oscarsidebo/multi-client


      - name: Push server
        run: docker push oscarsidebo/multi-server


      - name: Push nginx
        run: docker push oscarsidebo/multi-nginx


      - name: Push worker
        run: docker push oscarsidebo/multi-worker


