name: Aws
on: 
  workflow_run: 
    workflows: ["Docker Flow"] 
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test 
        run: echo IM RUNNING NOW
