name: Docker Flow
on: 
  push: 
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout 
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t oscarsidebo/react-test -f ./client/Dockerfile.dev ./client

      - name: Run test suite
        run: docker run -e CI=true oscarsidebo/react-test npm run test

